######################################################################
#
# File name : tb_Line_Shift_RAM_wave.do
# Created on: Tue Jan 02 13:38:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
