######################################################################
#
# File name : tb_Line_Shift_RAM_simulate.do
# Created on: Tue Jan 02 15:22:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_Line_Shift_RAM xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_Line_Shift_RAM_wave.do}

view wave
view structure
view signals

do {tb_Line_Shift_RAM.udo}

run 1000ns
