######################################################################
#
# File name : tb_Line_Shift_RAM_compile.do
# Created on: Tue Jan 02 15:22:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../../rtl/Line_Shift_RAM.v" \
"../../../../../../sim/tb_Line_Shift_RAM.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

