# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.srcs/sources_1/ip/fifo_8_sys/fifo_8_sys.xci
# IP: The module: 'fifo_8_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.gen/sources_1/ip/fifo_8_sys/fifo_8_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8_sys'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.gen/sources_1/ip/fifo_8_sys/fifo_8_sys_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.gen/sources_1/ip/fifo_8_sys/fifo_8_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.srcs/sources_1/ip/fifo_8_sys/fifo_8_sys.xci
# IP: The module: 'fifo_8_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.gen/sources_1/ip/fifo_8_sys/fifo_8_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.gen/sources_1/ip/fifo_8_sys/fifo_8_sys_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/fpga_IP_define/Axi_DMA/prj/Axi_DMA/Axi_DMA.gen/sources_1/ip/fifo_8_sys/fifo_8_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
