######################################################################
#
# File name : tb_bayer2rgb_3x3_simulate.do
# Created on: Fri Jan 05 13:04:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_bayer2rgb_3x3 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_bayer2rgb_3x3_wave.do}

view wave
view structure
view signals

do {tb_bayer2rgb_3x3.udo}

run 1000ns
