######################################################################
#
# File name : tb_bayer2rgb_3x3_wave.do
# Created on: Fri Jan 05 13:04:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
